## Numpy
- NumPy(or Numpy) is a linear algebra library for python, the reason it is so important for data science with python is that almost all the libraries in the PyData Ecosystem rely on Numpy as one of their main building blocks.
- Numpy is also incredibly fast, as it has bindings to C libraries.
- Numerical Python.

In [1]:
import numpy as np

- many built in functions and capabilites. 
- some of the most important aspects of Numpy: vectors, arrays, matrices and number generation.

###  Numpy Arrays
- Numpy arrays are the main way we will use numpy throughout the course.
- Two flavours: 1) Vectors, 2) matrices.
- Vectors - strictly 1-d arrays, matrices are 2-d

## Creating Numpy Arrays
- from a python list


In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
a = np.array(my_matrix)

In [7]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a.shape

(3, 3)

### Built-in Methods
- There are lots of built in ways to generate Arrays.

## Arange
- return evenly spaced values within a given interval

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

## Zeros and Ones
- Generate arrays of zeros or ones


In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 2) Linspace
- Return evenly spaced Numbers over a specified interval.

In [22]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [24]:
10/49

0.20408163265306123

### Eye 
- creates an identity matrix

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random
- Create an array of the given shape and populate it with random samples from a uniform distribution over [0,1]

In [27]:
np.random.rand(2)

array([0.02056481, 0.10263001])

In [28]:
np.random.rand(3,2)

array([[0.92065738, 0.76116272],
       [0.97604004, 0.75248798],
       [0.07990955, 0.40766724]])

In [29]:
np.random.rand(3,2)

array([[0.46255329, 0.1923574 ],
       [0.49669738, 0.52492975],
       [0.12720526, 0.34197275]])

### randn
- return a sample (or samples) from the 'standard normal' distribution. unlike rand which is uniform.

In [35]:
np.random.randn(2)

array([0.19989262, 0.27043896])

In [31]:
np.random.randn(4,5)

array([[ 0.30235384,  0.96895144, -1.56963912,  1.1117049 , -1.37951062],
       [-2.09540726,  0.37190327, -1.12599305, -0.2839002 , -0.27784276],
       [ 0.09636626, -0.28489941, -0.03660544, -0.57446594,  0.92511685],
       [-0.23847675,  0.16380482, -0.11468384, -0.8524423 , -0.64621225]])

In [36]:
list =  [0.30235384,  0.96895144, -1.56963912,  1.1117049 , -1.37951062,
       -2.09540726,  0.37190327, -1.12599305, -0.2839002 , -0.27784276,
        0.09636626, -0.28489941, -0.03660544, -0.57446594,  0.92511685,
       -0.23847675,  0.16380482, -0.11468384, -0.8524423 , -0.64621225]

In [37]:
np.mean(list)

-0.27699387799999997

### Randint
- returns random integers from low(inclusive) to high (exclusive)


In [38]:
np.random.randint(1,100)

53

In [39]:
np.random.randint(1,100)

35

In [40]:
np.random.randint(1,100)

14

In [41]:
np.random.randint(1,100)

47

In [42]:
np.random.randint(1,100,10)

array([63, 50, 28,  9, 47, 82,  5, 67, 70, 25])

## Arrays attributes and Methods
- lets discuss some useful attributes and methods of an array.

In [43]:
arr = np.arange(25)
abc = np.random.randint(0,50,10)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
abc

array([32, 18, 29, 29, 16, 23, 23, 36, 43, 42])

## Reshape
- Returns an array containing the same data with a new shape.

In [46]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

- Max,min, argmax, argmin
- These are useful methods for finding max or min values. or to find their index locations using argmin and argmax

In [47]:
abc

array([32, 18, 29, 29, 16, 23, 23, 36, 43, 42])

In [48]:
abc.max()

43

In [50]:
abc.min()

16

In [49]:
abc.argmax()

8

In [52]:
abc.argmin() #index position of the min value

4

## Shape
- shape is an attribute that arrays have(not a method)

In [54]:
abc.shape

(10,)

In [55]:
#Notice the two sets of brackets
arr.shape

(25,)

In [56]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [61]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [58]:
arr.shape

(25,)

In [59]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

### dtype


In [62]:
arr.dtype

dtype('int32')

## Numpy Indexing and selection
- In this session, we will discuss how to select elements or groups of elements from an array.

In [63]:
import numpy as np


In [69]:
#creating sample array
arr = np.arange(0.5,10.5)

In [70]:
arr

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [71]:
arr[0]

0.5

In [72]:
arr[4]

4.5

In [73]:
arr[1:5]

array([1.5, 2.5, 3.5, 4.5])

In [74]:
arr[0:5]

array([0.5, 1.5, 2.5, 3.5, 4.5])

## Broadcasting
- Numpy arrays differ from a normal python list because of their ability to broadcast

In [75]:
#setting a value with index range(Broadcasting)

In [77]:
arr[0:5] = 100

In [78]:
arr

array([100. , 100. , 100. , 100. , 100. ,   5.5,   6.5,   7.5,   8.5,
         9.5])

In [79]:
arr

array([100. , 100. , 100. , 100. , 100. ,   5.5,   6.5,   7.5,   8.5,
         9.5])

In [81]:
#Reset array, we will see why I had to reset in a moment
arr = np.arange(0.5,10.5)

In [82]:
arr

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [83]:
xyz = arr[0:6]

In [84]:
xyz

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5])

In [86]:
xyz[:] = 99

In [87]:
xyz

array([99., 99., 99., 99., 99., 99.])

In [89]:
array_copy = xyz.copy()

In [90]:
array_copy

array([99., 99., 99., 99., 99., 99.])

## Indexing a 2D array(matrices)
- general format is arr_2d[row][col] or arr_2d[row,col]
- I recomment to use comma notation for clarity.

In [93]:
arr_2d = np.array(([5,10,15], [20,25,30], [35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [94]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [95]:
arr_2d[1][2]

30

In [97]:
arr_2d[1,2]

30

In [98]:
#2d array slicing
arr_2d[:2 , 1: ]

array([[10, 15],
       [25, 30]])

In [100]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [99]:
arr_2d[2]

array([35, 40, 45])

In [101]:
arr_2d[2, :]

array([35, 40, 45])

## Fancy Indexing

In [142]:
#set up the matrix
arr2d = np.zeros((10,10))

In [143]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [132]:
a = np.zeros((3,3))

In [133]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [134]:
arr2d.shape

(10, 10)

In [135]:
#length of array
arr_length = arr2d.shape[1]

In [136]:
arr_length

10

In [137]:
#set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [138]:
#fancy indexing

In [139]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [140]:
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Selection
- lets briefly go over how to use brackets for selection based off of comparision operators



In [114]:
arr = np.arange(1,11)

In [115]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [144]:
bool_arr = arr>4

In [145]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

## Numpy Operations


### 1) Arithmetic
- you can easily perform array with array arithmetic or scalar with array arithmetic.
- e.g

In [149]:
import numpy as np
arr = np.arange(0,10)

In [150]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [151]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [153]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [154]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [155]:
arr / arr

<ipython-input-155-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [156]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

## universal array functions
- useful to perform the operations across the array.

In [157]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [158]:
#calculating exponential (e^)

In [159]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [160]:
np.max(arr)

9

In [161]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [162]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [163]:
np.log(arr)

<ipython-input-163-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Thats all we need to know for now!!